
import com.hi.techpoints.model.Product

rule "Offer for Iphone"
	when 
		productObject: Product(model == "Iphone")
	then
		productObject.setDiscount(5);
		System.out.println("Offer for Iphone");
	end
	
rule "Offer for Pixel"
salience 10
activation-group "Pixel Mobile"
	when 
		productObject: Product(model == "Pixel")
	then
		productObject.setDiscount(10);
		System.out.println("Offer for pixel");
	end
	
rule "Offer for Pixel on New Year Sale"
salience 20
activation-group "Pixel Mobile"
	when 
		productObject: Product(model == "Pixel" && event == "Sale")
	then
	    productObject.setDiscount(15);
		System.out.println("Offer for Pixel on New Year Sale");
	end	